### ISSUE TITLE
Mayor job isn't repealed if the player is no longer mayor

### ISSUE THREAD

**Issue by homosapine** [cityrpg/Blockland-CityRPG-4#9] opened 2020-01-06 21:17 UTC
This possibly can only happen if the player is offline when they lose their mayor status but I'm not sure

**Comment by LakeYS** [comment] 2020-01-07 01:11
I believe this is caused by the mayor spot blanking itself out when the server restarts, without actually removing the existing mayor.

This can be theoretically fixed by saving and reloading the mayor value (as it should anyway), however a more foolproof solution might be to implement an additional check when the mayor joins.

As a workaround, I'll do occasional passes on the save data to ensure people aren't holding out with the mayor job.

**Comment by Dglider** [comment] 2020-01-09 08:01
I would just do a check when a player joins.

**Comment by LakeYS** [comment] 2020-01-18 13:37
It turns out there already is a check buried in the tick loop, it was just checking for the wrong job. This is being fixed.

**Closed** 2020-01-18 13:39 UTC
Labels: bug, critical
